### ISSUE TITLE
Not working with Gutenberg plugin (10.5.4)

### ISSUE THREAD

**Issue by intelligence** [joppuyo/remove-drop-cap#3]
Not sure what's breaking with recent Gutenberg development, but the Drop cap setting is back again 😩

**Comment by joppuyo** [comment]
Hey,

That's too bad. Unfortunately, the Gutenberg plugin is too unstable for me to support. If this issue exists when WordPress 5.8 is released, I will have to find a way to restore the option to disable the drop cap.

**Comment by intelligence** [comment]
Totally understandable, I'm not sure why I punish myself with bleeding edge stuff with Gutenberg, feels like it comes tumbling down every other week with breaking changes.

**Comment by joppuyo** [comment]
Yeah, the plugin is great if you are really invested in GB development, not so much if you want a stable foundation to build something on.

I'm closing this for now. I'll try to fix any potential compatibility issues proactively when WordPress 5.8 RC is released.
