### ISSUE TITLE
New location in WP 5.8

### ISSUE THREAD

**Issue by adriantoll** [joppuyo/remove-drop-cap#4]
The setting has now moved to:

`$editor_settings['__experimentalFeatures']['typography']['dropCap']`

So they've removed the `['default']` part.

**Comment by joppuyo** [comment]
Big thanks for the research, weird that it’s still under __experimentalFeatures even if theme.json is supposed to be stable in 5.8 🤔

I’ll release a new version soon with this code!

**Comment by joppuyo** [comment]
Fixed in v1.3.0
