### ISSUE TITLE
Plugin in WordPress.org ?

### ISSUE THREAD

**Issue by Romaixn** [joppuyo/remove-drop-cap#5]
Hello ! Thanks for this plugin. It's work like a charm !

I have a question : Why not putting you in wordpress.org plugins ? to have automatic update, etc..

**Comment by joppuyo** [comment]
Glad you like it!

It's my plan to eventually have this plugin in the w.org repository 🙂

**Comment by joppuyo** [comment]
I have just submitted the plugin in the WordPress.org plugin directory, let's see when it gets approved.

**Comment by joppuyo** [comment]
This plugin is now available here: https://wordpress.org/plugins/disable-drop-cap/
